# Generated by Django 5.0.6 on 2024-06-16 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_showtime_showtime_start_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seat',
            name='row',
            field=models.CharField(max_length=10),
        ),
    ]
