# Generated by Django 5.0.6 on 2024-06-16 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_seat_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='showtime',
            name='ticket_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
    ]
