# Generated by Django 5.0.6 on 2024-06-16 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_showtime_ticket_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='showtime',
            name='ticket_price',
            field=models.DecimalField(decimal_places=2, default=2.394, max_digits=6),
        ),
    ]
